import Database from 'better-sqlite3';
import { drizzle } from 'drizzle-orm/better-sqlite3';
import { migrate } from 'drizzle-orm/better-sqlite3/migrator';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import * as schema from './schema.js';

export type SecondBrainDb = ReturnType<typeof drizzle<typeof schema>>;

const __dirname = path.dirname(fileURLToPath(import.meta.url));

/** Migrations folder packaged with the CLI (generated by drizzle-kit). */
export function migrationsFolder(): string {
  return path.resolve(__dirname, '../../../drizzle');
}

export function openSecondBrainDatabase(databaseFilePath: string): SecondBrainDb {
  const sqlite = new Database(databaseFilePath);
  sqlite.pragma('journal_mode = WAL');
  sqlite.pragma('foreign_keys = ON');
  return drizzle(sqlite, { schema });
}

export function runMigrations(db: SecondBrainDb): void {
  migrate(db, { migrationsFolder: migrationsFolder() });
}

export function openAndMigrate(databaseFilePath: string): SecondBrainDb {
  const db = openSecondBrainDatabase(databaseFilePath);
  runMigrations(db);
  return db;
}

/** Close the underlying better-sqlite3 handle (required before deleting the file on Windows). */
export function closeSecondBrainDatabase(db: SecondBrainDb): void {
  const client = (db as unknown as { $client?: { close: () => void } }).$client;
  if (client !== undefined) {
    client.close();
  }
}
